
package com.mycompany.company.ambulancia;


import com.mycompany.company.Inicio;
import com.mycompany.company.conectarDB.conectarBaseDeDatos;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;




public class inventario_ambu extends javax.swing.JFrame {
   public JTable tabla;
   public String x;
    private Connection conexion;
    public inventario_ambu() {
        initComponents();
        rellenar();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtsuministros = new javax.swing.JTable();
        btn_volver = new javax.swing.JButton();
        btn_añadirSum = new javax.swing.JButton();
        btn_removerSum = new javax.swing.JButton();
        jid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcantidad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jfecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jnombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        lbl_num_amb = new javax.swing.JLabel();
        jComboBox_num_amb = new javax.swing.JComboBox<>();
        lbl_add_sum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jtsuministros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 770, 350));

        btn_volver.setBackground(new java.awt.Color(51, 102, 0));
        btn_volver.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(242, 242, 242));
        btn_volver.setText("Volver");
        btn_volver.setToolTipText("");
        btn_volver.setBorder(null);
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 650, 90, 50));

        btn_añadirSum.setBackground(new java.awt.Color(51, 102, 0));
        btn_añadirSum.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btn_añadirSum.setForeground(new java.awt.Color(242, 242, 242));
        btn_añadirSum.setText("Añadir nuevo insumo");
        btn_añadirSum.setToolTipText("");
        btn_añadirSum.setBorder(null);
        btn_añadirSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirSumActionPerformed(evt);
            }
        });
        jPanel1.add(btn_añadirSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 240, 30));

        btn_removerSum.setBackground(new java.awt.Color(204, 204, 204));
        btn_removerSum.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btn_removerSum.setForeground(new java.awt.Color(242, 242, 242));
        btn_removerSum.setText("Remover insumo");
        btn_removerSum.setToolTipText("");
        btn_removerSum.setBorder(null);
        btn_removerSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerSumActionPerformed(evt);
            }
        });
        jPanel1.add(btn_removerSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 220, 30));

        jid.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 240, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 120, 20));

        jcantidad.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jcantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, 240, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 120, 20));

        jfecha.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jfecha.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 240, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel2.setText("Fecha de Expiración");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 420, 160, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 120, 20));

        jnombre.setBackground(new java.awt.Color(255, 255, 255));
        jnombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jnombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 240, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 380, -1, -1));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\paula\\Documents\\NetBeansProjects\\company\\src\\main\\java\\img\\planta fondo.png")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 480, 720));

        lbl_num_amb.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        lbl_num_amb.setForeground(new java.awt.Color(153, 153, 153));
        lbl_num_amb.setText("Elige el número de ambulancia:");
        jPanel1.add(lbl_num_amb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 290, 50));

        jComboBox_num_amb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_num_ambItemStateChanged(evt);
            }
        });
        jComboBox_num_amb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_num_ambActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_num_amb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 170, 50));

        lbl_add_sum.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        lbl_add_sum.setForeground(new java.awt.Color(51, 153, 0));
        lbl_add_sum.setText("Actualizar Suministros ");
        jPanel1.add(lbl_add_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 450, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_num_ambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_num_ambActionPerformed
        this.x = String.valueOf(jComboBox_num_amb.getSelectedItem());
       System.out.println(x);
       llenarTabla();
    }//GEN-LAST:event_jComboBox_num_ambActionPerformed

    private void jComboBox_num_ambItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_num_ambItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_num_ambItemStateChanged

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed

        // TODO add your handling code here:
        Inicio volver = new Inicio();
        volver.setVisible(true);

    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_añadirSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirSumActionPerformed
                      
             new ActualizarAmbulancia().setVisible(true);
    }//GEN-LAST:event_btn_añadirSumActionPerformed

    private void btn_removerSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerSumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_removerSumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rellenar(){
        
     conexion= conectarBaseDeDatos.conectarBaseDeDatos();
        String query =  "SELECT AMBU_NUM FROM SUMINISTROS GROUP BY AMBU_NUM";
           
        try{  
           Statement pst = conexion.createStatement();
           ResultSet rs = pst.executeQuery(query);
           jComboBox_num_amb.addItem("Selecciona");
           
           
           while (rs.next()){
           jComboBox_num_amb.addItem(rs.getString("AMBU_NUM"));
           
           }
          System.out.println( jComboBox_num_amb.getSelectedItem());
            rs.close();
            }    
        catch (SQLException e){
        JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    
    private void llenarTabla(){
        
    this.setLocationRelativeTo(this.tabla);
        
    DefaultTableModel dfm = new DefaultTableModel();
    tabla = this.jtsuministros;
    tabla.setModel(dfm);
    
    dfm.setColumnIdentifiers(new Object[]{"Suministro ID", "Nombre", "cantidad", "Fecha de exp"});
    
    conexion= conectarBaseDeDatos.conectarBaseDeDatos();
    String query =  "SELECT SUM_ID, SUB_NOMBRE,CANTIDAD, FECHA_EXP FROM SUMINISTROS WHERE AMBU_NUM="+x;
    try{
        Statement pst = conexion.createStatement();
           ResultSet rs = pst.executeQuery(query);
           while(rs.next()){
           dfm.addRow(new Object[]{rs.getInt("SUM_ID"),rs.getString("SUB_NOMBRE"),rs.getInt("CANTIDAD"),rs.getDate("FECHA_EXP")});
           }
    jtsuministros.addMouseListener(new MouseAdapter(){

            public void mousePressed(MouseEvent Mouse_evt){
            System.out.println("prueba");
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point); 

                if (Mouse_evt.getClickCount()==1)
                {
                jid.setText(jtsuministros.getValueAt(jtsuministros.getSelectedRow(),0).toString());
                jnombre.setText(jtsuministros.getValueAt(jtsuministros.getSelectedRow(),1).toString());
                jcantidad.setText(jtsuministros.getValueAt(jtsuministros.getSelectedRow(),2).toString());
                jfecha.setText(jtsuministros.getValueAt(jtsuministros.getSelectedRow(),3).toString());
                }
            }
            });
    
    }catch(Exception e){
    JOptionPane.showMessageDialog(this, e);
    }
    
    }
   
    
    
    
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirSum;
    private javax.swing.JButton btn_removerSum;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_num_amb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jcantidad;
    private javax.swing.JLabel jfecha;
    private javax.swing.JLabel jid;
    private javax.swing.JLabel jnombre;
    private javax.swing.JTable jtsuministros;
    private javax.swing.JLabel lbl_add_sum;
    private javax.swing.JLabel lbl_num_amb;
    // End of variables declaration//GEN-END:variables
}
