
package com.mycompany.company;

import com.mycompany.company.almacen.inventario_almacen;
import com.mycompany.company.ambulancia.inventario_ambu;
import com.mycompany.company.personal.addPersonal;


public class Inicio extends javax.swing.JFrame {

    
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inventarioamb = new javax.swing.JButton();
        addpersonal = new javax.swing.JButton();
        inventarioamb1 = new javax.swing.JButton();
        fondoinicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 500, 120));

        inventarioamb.setBackground(new java.awt.Color(51, 102, 0));
        inventarioamb.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        inventarioamb.setForeground(new java.awt.Color(255, 255, 255));
        inventarioamb.setText("Almacén");
        inventarioamb.setToolTipText("Añadir personal");
        inventarioamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioambActionPerformed(evt);
            }
        });
        jPanel1.add(inventarioamb, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 330, 90));

        addpersonal.setBackground(new java.awt.Color(51, 102, 0));
        addpersonal.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        addpersonal.setForeground(new java.awt.Color(242, 242, 242));
        addpersonal.setText("Añadir Personal");
        addpersonal.setToolTipText("");
        addpersonal.setBorder(null);
        addpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpersonalActionPerformed(evt);
            }
        });
        jPanel1.add(addpersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 330, 90));

        inventarioamb1.setBackground(new java.awt.Color(51, 102, 0));
        inventarioamb1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        inventarioamb1.setForeground(new java.awt.Color(255, 255, 255));
        inventarioamb1.setText("Ambulancia");
        inventarioamb1.setToolTipText("Añadir personal");
        inventarioamb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioamb1ActionPerformed(evt);
            }
        });
        jPanel1.add(inventarioamb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 330, 90));

        fondoinicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\paula\\Documents\\NetBeansProjects\\company\\src\\main\\java\\img\\tropicalfondo al 1.png")); // NOI18N
        jPanel1.add(fondoinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpersonalActionPerformed

        // TODO add your handling code here:
        addPersonal nuevo_empleado = new addPersonal();
        nuevo_empleado.setVisible(true);
       
    }//GEN-LAST:event_addpersonalActionPerformed

    private void inventarioambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioambActionPerformed
        // TODO add your handling code here:
        inventario_almacen inv = new inventario_almacen();
        inv.setVisible(true);
        
    }//GEN-LAST:event_inventarioambActionPerformed

    private void inventarioamb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioamb1ActionPerformed
        inventario_ambu inventario = new inventario_ambu();
        inventario.setVisible(true);
    }//GEN-LAST:event_inventarioamb1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpersonal;
    private javax.swing.JLabel fondoinicio;
    private javax.swing.JButton inventarioamb;
    private javax.swing.JButton inventarioamb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
