
package com.mycompany.company;

import com.mycompany.company.conectarDB.conectarBaseDeDatos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class LoginFrame extends javax.swing.JFrame {
    private Connection conexion;
    
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagengrande = new javax.swing.JLabel();
        textocredenciales = new javax.swing.JLabel();
        txtidempleados = new javax.swing.JTextField();
        textoconstrasena = new javax.swing.JLabel();
        txtcontrasena = new javax.swing.JTextField();
        checkbxusuario = new javax.swing.JCheckBox();
        btnlogin = new javax.swing.JButton();
        btnolvido = new javax.swing.JButton();
        txtemplado = new javax.swing.JLabel();
        textlogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagengrande.setIcon(new javax.swing.ImageIcon("C:\\Users\\paula\\Documents\\NetBeansProjects\\company\\src\\main\\java\\img\\monstera peque.jpg")); // NOI18N
        imagengrande.setText("jLabel1");
        jPanel1.add(imagengrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 610));

        textocredenciales.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        textocredenciales.setForeground(new java.awt.Color(102, 102, 102));
        textocredenciales.setText("Introduce tus credenciales");
        jPanel1.add(textocredenciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 300, 20));

        txtidempleados.setForeground(new java.awt.Color(0, 51, 0));
        txtidempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidempleadosActionPerformed(evt);
            }
        });
        jPanel1.add(txtidempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 310, 40));

        textoconstrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoconstrasena.setForeground(new java.awt.Color(102, 102, 102));
        textoconstrasena.setText("Contraseña");
        jPanel1.add(textoconstrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 170, 30));

        txtcontrasena.setForeground(new java.awt.Color(51, 51, 0));
        txtcontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(txtcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 310, 40));

        checkbxusuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkbxusuario.setForeground(new java.awt.Color(102, 102, 102));
        checkbxusuario.setText("Recordar Usuario");
        checkbxusuario.setBorder(null);
        checkbxusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbxusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(checkbxusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 140, 30));

        btnlogin.setBackground(new java.awt.Color(0, 153, 51));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("Login");
        btnlogin.setBorder(null);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 310, 30));

        btnolvido.setForeground(new java.awt.Color(153, 153, 153));
        btnolvido.setText("¿Olvidaste tu contraseña?");
        btnolvido.setBorder(null);
        jPanel1.add(btnolvido, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 470, 180, 30));

        txtemplado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtemplado.setForeground(new java.awt.Color(102, 102, 102));
        txtemplado.setText("ID de Empleado");
        jPanel1.add(txtemplado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 140, 30));

        textlogin.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        textlogin.setForeground(new java.awt.Color(102, 102, 102));
        textlogin.setText("Login");
        jPanel1.add(textlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtidempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidempleadosActionPerformed
        // ID DE EMPLEADO TEXT FIELD
       
        
         
    }//GEN-LAST:event_txtidempleadosActionPerformed

    private void checkbxusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbxusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbxusuarioActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // LOGIN button
        String id_empleado = txtidempleados.getText();
        String contrasena= txtcontrasena.getText();
        if (id_empleado.isEmpty()||contrasena.isEmpty()){
          JOptionPane.showMessageDialog(this, "Por favor complete todos los campos.");  
        }
        
        else{
            if (checkDB(id_empleado)){
            JOptionPane.showMessageDialog(this, "Empleado en base de datos");
            Inicio nuevo = new Inicio(); 
            nuevo.setVisible(true);
            this.dispose();
            }
            else{
            JOptionPane.showMessageDialog(this, "Empleado no está en la base de datos");
            }
        } 
        
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtcontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontrasenaActionPerformed

    }//GEN-LAST:event_txtcontrasenaActionPerformed
    
    
    
    public boolean checkDB(String id_empleado){
        
        try{
       conexion= conectarBaseDeDatos.conectarBaseDeDatos();
        
        
        String query = "SELECT EMPLEADOS_ID FROM EMPLEADOS WHERE EMPLEADOS_ID = ?" ;   
        PreparedStatement pst = conexion.prepareStatement(query);
        pst.setInt(1, Integer.parseInt(id_empleado));

        ResultSet rs = pst.executeQuery();
        
        // Verificar si hay resultados
        if (rs.next()) {
            return true;  // El empleado existe en la base de datos
        } else {
            return false;  // El empleado no existe
        }
    } catch (SQLException e) {
        // Manejo de errores
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
        return false;
    }
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnolvido;
    private javax.swing.JCheckBox checkbxusuario;
    private javax.swing.JLabel imagengrande;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textlogin;
    private javax.swing.JLabel textoconstrasena;
    private javax.swing.JLabel textocredenciales;
    private javax.swing.JTextField txtcontrasena;
    private javax.swing.JLabel txtemplado;
    private javax.swing.JTextField txtidempleados;
    // End of variables declaration//GEN-END:variables


}
