
package com.mycompany.company.almacen;

import com.mycompany.company.conectarDB.conectarBaseDeDatos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


public class ActualizarAlmacen extends javax.swing.JFrame {
    
    private Connection conexion;
    
    public ActualizarAlmacen()
   
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_add_sum = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jTextCantidad = new javax.swing.JTextField();
        jTextFecha = new javax.swing.JTextField();
        jTextnombre = new javax.swing.JTextField();
        btn_añadirSum1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 120, 20));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 120, 20));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 120, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel2.setText("Fecha de Expiración:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 160, 20));

        lbl_add_sum.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        lbl_add_sum.setText("Registro de nuevo insumo");
        jPanel1.add(lbl_add_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 250, 50));

        btn_volver.setBackground(new java.awt.Color(51, 102, 0));
        btn_volver.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(242, 242, 242));
        btn_volver.setText("Volver");
        btn_volver.setToolTipText("");
        btn_volver.setBorder(null);
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 90, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 10)); // NOI18N
        jLabel5.setText("Formato de fecha debe ser AAAA/MM/DD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 200, -1));

        jTextId.setBackground(new java.awt.Color(242, 242, 242));
        jTextId.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jTextId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });
        jPanel1.add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 240, 50));

        jTextCantidad.setBackground(new java.awt.Color(242, 242, 242));
        jTextCantidad.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jTextCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 240, 50));

        jTextFecha.setBackground(new java.awt.Color(242, 242, 242));
        jTextFecha.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jTextFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 240, 50));

        jTextnombre.setBackground(new java.awt.Color(242, 242, 242));
        jTextnombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jTextnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 240, 50));

        btn_añadirSum1.setBackground(new java.awt.Color(51, 102, 0));
        btn_añadirSum1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btn_añadirSum1.setForeground(new java.awt.Color(242, 242, 242));
        btn_añadirSum1.setText("Guardar");
        btn_añadirSum1.setToolTipText("");
        btn_añadirSum1.setBorder(null);
        btn_añadirSum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirSum1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_añadirSum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 170, 30));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\paula\\Documents\\NetBeansProjects\\company\\src\\main\\java\\img\\panel.png")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
            new inventario_almacen();
            
        
    }//GEN-LAST:event_btn_volverActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jTextCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCantidadActionPerformed

    private void jTextFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaActionPerformed

    private void jTextnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnombreActionPerformed

    private void btn_añadirSum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirSum1ActionPerformed
        // TODO add your handling code here:
        addSuministros();
    }//GEN-LAST:event_btn_añadirSum1ActionPerformed

    private void addSuministros(){
    
        String nombre = jTextnombre.getText();
        String id = jTextId.getText();
        String cantidad = jTextCantidad.getText();
        String fecha_exp = jTextFecha.getText();
        
        if (nombre.isEmpty()|| id.isEmpty()|| cantidad.isEmpty()|| fecha_exp.isEmpty()){
        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos");
        }
        else{
        conexion= conectarBaseDeDatos.conectarBaseDeDatos();
         
     java.sql.Date sqlDate = null;
        try {
            // Convertir la fecha de String a java.sql.Date
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            java.util.Date utilDate = sdf.parse(fecha_exp); // Convertir el String a java.util.Date
            sqlDate = new java.sql.Date(utilDate.getTime()); // Convertir java.util.Date a java.sql.Date
        } catch (ParseException e) {
            // Mostrar mensaje de error si la fecha no tiene el formato esperado
            JOptionPane.showMessageDialog(this, "La fecha debe tener el formato AAAA/MM/DD.");
            e.printStackTrace();
            return;
        }
        
        
        try {
            // Crear una consulta SQL para ingresarr el suministro
            String query = "INSERT INTO ALMACEN (SUM_NOMBRE,SUM_ID, CANTIDAD, FECHA_EXP) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conexion.prepareStatement(query);
            
            pst.setString(1, nombre);
            pst.setInt(2, Integer.parseInt(id));
            pst.setInt(3, Integer.parseInt(cantidad));
            pst.setDate(4,sqlDate);
                    
            int filasAfectadas = pst.executeUpdate();
            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(this, "Suministro registrado correctamente.");
            } 
            pst.close();   
            
            
            
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al realizar el registro: " + e.getMessage());
                e.printStackTrace();
            }   
        
           inventario_almacen cargar = new inventario_almacen();
           cargar.iniciarTabla();
        }
              
    }
               

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirSum1;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextnombre;
    private javax.swing.JLabel lbl_add_sum;
    // End of variables declaration//GEN-END:variables
}
