
package com.mycompany.company.almacen;

import com.mycompany.company.Inicio;
import com.mycompany.company.conectarDB.conectarBaseDeDatos;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class inventario_almacen extends javax.swing.JFrame {
    
    private Connection conexion;
    
    public inventario_almacen() {
        initComponents();
        iniciarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtsuministros = new javax.swing.JTable();
        btn_añadirSum = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jnombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcantidad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jfecha = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        lbl_add_sum = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jtsuministros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 770, 350));

        btn_añadirSum.setBackground(new java.awt.Color(51, 102, 0));
        btn_añadirSum.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btn_añadirSum.setForeground(new java.awt.Color(242, 242, 242));
        btn_añadirSum.setText("Añadir nuevo insumo");
        btn_añadirSum.setToolTipText("");
        btn_añadirSum.setBorder(null);
        btn_añadirSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirSumActionPerformed(evt);
            }
        });
        jPanel1.add(btn_añadirSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 240, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 150, 120, 20));

        jnombre.setBackground(new java.awt.Color(255, 255, 255));
        jnombre.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jnombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 240, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 120, 20));

        jid.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jid.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 240, 40));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, 120, 20));

        jcantidad.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jcantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 240, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel2.setText("Fecha de Expiración");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, 160, 20));

        jfecha.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jfecha.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 420, 240, 40));

        btn_volver.setBackground(new java.awt.Color(51, 102, 0));
        btn_volver.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(242, 242, 242));
        btn_volver.setText("Volver");
        btn_volver.setToolTipText("");
        btn_volver.setBorder(null);
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, 90, 50));

        lbl_add_sum.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        lbl_add_sum.setForeground(new java.awt.Color(51, 153, 0));
        lbl_add_sum.setText("Almacén ");
        jPanel1.add(lbl_add_sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 450, 70));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\paula\\Documents\\NetBeansProjects\\company\\src\\main\\java\\img\\planta opaca.png")); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 480, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_añadirSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirSumActionPerformed
        new ActualizarAlmacen().setVisible(true);
      //ActualizarAlmacen add = new ActualizarAlmacen();
      //add.setVisible(true);
    }//GEN-LAST:event_btn_añadirSumActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed

        // TODO add your handling code here:
        Inicio volver = new Inicio();
        volver.setVisible(true);
    }//GEN-LAST:event_btn_volverActionPerformed

    
    public void iniciarTabla(){
    
        conexion= conectarBaseDeDatos.conectarBaseDeDatos();
        this.setLocationRelativeTo(this.jtsuministros);
        System.out.println("prueba");
        DefaultTableModel dfm = new DefaultTableModel();
        jtsuministros = this.jtsuministros;
        jtsuministros.setModel(dfm);

        dfm.setColumnIdentifiers(new Object[]{"Suministro ID", "Nombre", "cantidad", "Fecha de exp"});
        
        String query =  "SELECT SUM_ID, SUM_NOMBRE,CANTIDAD, FECHA_EXP FROM ALMACEN";
        try{
        Statement pst = conexion.createStatement();
           ResultSet rs = pst.executeQuery(query);
           while(rs.next()){
           dfm.addRow(new Object[]{rs.getInt("SUM_ID"),rs.getString("SUM_NOMBRE"),rs.getInt("CANTIDAD"),rs.getDate("FECHA_EXP")});
           }
           jtsuministros.addMouseListener(new MouseAdapter(){

            public void mousePressed(MouseEvent Mouse_evt){
            
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point); 

                if (Mouse_evt.getClickCount()==1)
                {
                jid.setText(jtsuministros.getValueAt(jtsuministros.getSelectedRow(),0).toString());
                jnombre.setText(jtsuministros.getValueAt(jtsuministros.getSelectedRow(),1).toString());
                jcantidad.setText(jtsuministros.getValueAt(jtsuministros.getSelectedRow(),2).toString());
                jfecha.setText(jtsuministros.getValueAt(jtsuministros.getSelectedRow(),3).toString());
                }
            }
            });
           
           }catch(SQLException e){}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirSum;
    private javax.swing.JButton btn_volver;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jcantidad;
    private javax.swing.JLabel jfecha;
    private javax.swing.JLabel jid;
    private javax.swing.JLabel jnombre;
    private javax.swing.JTable jtsuministros;
    private javax.swing.JLabel lbl_add_sum;
    // End of variables declaration//GEN-END:variables
}
